backend:
  name: git-gateway
   

collections: 
  - name: "posts"
    label: "Meetup Notes"
    folder: "posts"
    create: true
    slug: "{{ slug }}"
    fields: 
      - {
        label: "Title", 
        name: "title",
        widget: "string"
      }
      - {
        label: "Publish Date",
        name: "date",
        widget: "datetime"
      }
      - {
        label: "Post Body",
        name: "body",
        widget: "markdown"
      }


media_folder: "images" # Media files will be stored in the repo under images/uploads
